// ========================================
// Capital - Definição das 23 Cartas (x4 = 92)
// ========================================

export const CARD_TYPES = {
  // === CARTAS DE AÇÃO (18 tipos) ===
  dinheiro_facil: {
    id: 'dinheiro_facil',
    name: 'Dinheiro Fácil',
    description: 'Receba $500 da Prefeitura.',
    cost: 0,
    type: 'action',
    targetType: 'self',
    duration: null,
    icon: '💰',
  },
  seguro_empresarial: {
    id: 'seguro_empresarial',
    name: 'Seguro Empresarial',
    description: 'Seu saldo passa a ser $200.',
    cost: 0,
    type: 'action',
    targetType: 'self',
    duration: null,
    icon: '🛡️',
  },
  na_mira_do_leao: {
    id: 'na_mira_do_leao',
    name: 'Na Mira do Leão',
    description: 'Escolha um oponente. No próximo turno dele, paga 50% do saldo à Prefeitura.',
    cost: 200,
    type: 'action',
    targetType: 'opponent',
    duration: 1,
    icon: '🦁',
  },
  cobranca_mafia: {
    id: 'cobranca_mafia',
    name: 'Cobrança da Máfia',
    description: 'Escolha um oponente. No próximo turno dele, paga 30% do valor dos negócios a você.',
    cost: 100,
    type: 'action',
    targetType: 'opponent',
    duration: 1,
    icon: '🎩',
  },
  isencao_taxas: {
    id: 'isencao_taxas',
    name: 'Isenção de Taxas',
    description: 'Evite os próximos 3 pagamentos de Máfia, Pedágio ou Leão.',
    cost: 200,
    type: 'action',
    targetType: 'self',
    duration: 3,
    icon: '📜',
  },
  isencao_negocios: {
    id: 'isencao_negocios',
    name: 'Isenção de Negócios',
    description: 'Evite os próximos 3 pagamentos de rendimento a oponentes.',
    cost: 200,
    type: 'action',
    targetType: 'self',
    duration: 3,
    icon: '🏢',
  },
  conta_trancada: {
    id: 'conta_trancada',
    name: 'Conta Trancada',
    description: 'Escolha um oponente. O dinheiro que ele receber vai para a Prefeitura.',
    cost: 200,
    type: 'action',
    targetType: 'opponent',
    duration: 1,
    icon: '🔒',
  },
  cuidado_obras: {
    id: 'cuidado_obras',
    name: 'Cuidado, Obras',
    description: 'Coloque uma obstrução em uma casa. Só você ou quem tirar 6 consegue passar.',
    cost: 100,
    type: 'action',
    targetType: 'board',
    duration: null,
    icon: '🚧',
  },
  pedagio: {
    id: 'pedagio',
    name: 'Pedágio',
    description: 'Coloque um pedágio em uma casa. Jogadores pagam $100 ao passar.',
    cost: 100,
    type: 'action',
    targetType: 'board',
    duration: null,
    icon: '🚦',
  },
  demolicao: {
    id: 'demolicao',
    name: 'Demolição',
    description: 'Destrua uma obstrução ou pedágio do tabuleiro.',
    cost: 100,
    type: 'action',
    targetType: 'board',
    duration: null,
    icon: '💣',
  },
  operacao_lebre: {
    id: 'operacao_lebre',
    name: 'Operação Lebre',
    description: 'Seus dados sempre caem 6 pelos próximos 3 turnos.',
    cost: 0,
    type: 'action',
    targetType: 'self',
    duration: 3,
    icon: '🐇',
  },
  operacao_tartaruga: {
    id: 'operacao_tartaruga',
    name: 'Operação Tartaruga',
    description: 'Escolha um oponente. Os dados dele sempre caem 1 por 3 turnos.',
    cost: 200,
    type: 'action',
    targetType: 'opponent',
    duration: 3,
    icon: '🐢',
  },
  dado_dado: {
    id: 'dado_dado',
    name: 'Dado Dado',
    description: 'Ganhe +1 dado permanentemente (máximo 4).',
    cost: 200,
    type: 'action',
    targetType: 'self',
    duration: null,
    icon: '🎲',
  },
  dado_perdido: {
    id: 'dado_perdido',
    name: 'Dado Perdido',
    description: 'Escolha um oponente. Ele perde 1 dado permanentemente (mínimo 1).',
    cost: 500,
    type: 'action',
    targetType: 'opponent',
    duration: null,
    icon: '❌',
  },
  novo_comeco: {
    id: 'novo_comeco',
    name: 'Um Novo Começo',
    description: 'Escolha um oponente. Remove todos os efeitos temporários e reseta dados para 2.',
    cost: 200,
    type: 'action',
    targetType: 'opponent',
    duration: null,
    icon: '🔄',
  },
  implosao: {
    id: 'implosao',
    name: 'Implosão',
    description: 'Destrua um negócio de um oponente.',
    cost: 200,
    type: 'action',
    targetType: 'opponent_business',
    duration: null,
    icon: '💥',
  },
  valorizacao_instantanea: {
    id: 'valorizacao_instantanea',
    name: 'Valorização Instantânea',
    description: 'Escolha um de seus negócios. Ele sobe 3 níveis.',
    cost: 200,
    type: 'action',
    targetType: 'own_business',
    duration: null,
    icon: '📈',
  },
  marketing_agressivo: {
    id: 'marketing_agressivo',
    name: 'Marketing Agressivo',
    description: 'Todos os seus negócios sobem 1 nível.',
    cost: 400,
    type: 'action',
    targetType: 'self',
    duration: null,
    icon: '📢',
  },

  // === CARTAS DE VITÓRIA (5 tipos) ===
  mais_rico: {
    id: 'mais_rico',
    name: 'Mais Rico da Cidade',
    description: 'Vença se tiver 40%+ do patrimônio total e 2+ voltas completadas.',
    cost: 0,
    type: 'victory',
    targetType: 'self',
    icon: '👑',
  },
  empresario_sucesso: {
    id: 'empresario_sucesso',
    name: 'Empresário de Sucesso',
    description: 'Vença se tiver $7.000+ de patrimônio total.',
    cost: 0,
    type: 'victory',
    targetType: 'self',
    icon: '🏆',
  },
  jatinho: {
    id: 'jatinho',
    name: 'Jatinho Particular',
    description: 'Vença se tiver 2+ voltas a mais que todos os oponentes.',
    cost: 500,
    type: 'victory',
    targetType: 'self',
    icon: '✈️',
  },
  nadando_dinheiro: {
    id: 'nadando_dinheiro',
    name: 'Nadando em Dinheiro',
    description: 'Vitória instantânea!',
    cost: 3000,
    type: 'victory',
    targetType: 'self',
    icon: '🤑',
  },
  mega_negocio: {
    id: 'mega_negocio',
    name: 'Mega Negócio',
    description: 'Vença se qualquer negócio seu tiver $2.000+ de rendimento.',
    cost: 500,
    type: 'victory',
    targetType: 'self',
    icon: '🌟',
  },
};

// Lista de todos os IDs de cartas
export const ALL_CARD_IDS = Object.keys(CARD_TYPES);

// IDs das cartas de vitória
export const VICTORY_CARD_IDS = ALL_CARD_IDS.filter(id => CARD_TYPES[id].type === 'victory');

// IDs das cartas de ação
export const ACTION_CARD_IDS = ALL_CARD_IDS.filter(id => CARD_TYPES[id].type === 'action');

// Quantidade de cópias de cada carta no deck
export const COPIES_PER_CARD = 4;

// Total de cartas no deck
export const TOTAL_CARDS = ALL_CARD_IDS.length * COPIES_PER_CARD; // 92
